alpha version of xml2fdp
openspending/os-fdp-adapters pull request #1
Opened 2016-10-20 08:15 UTC by HimmelStein

depend on xml2csv package
install: 
 $ git clone https://github.com/wk0206/xml2csv
 $ npm install -g

2016-10-20 08:44 UTC, akariv commented
@HimmelStein I see the tests for this change are not passing.

Can you take a look and see that they do? If needed, you can install dependencies in the `.travis.yml` file.

2016-10-20 08:51 UTC, HimmelStein commented
failures are due to the missing of xml2csv command
please run install xml2csv package on the local machine:
$ git clone https://github.com/wk0206/xml2csv
$ npm install -g

2016-10-20 09:56 UTC, HimmelStein commented
@akariv failed to run "npm install -g"
log message is that: Permission denied.  fatal: Could not read from remote repository.
however, I can execute "npm install -g" on my local machine.

2016-10-24 04:54 UTC, akariv requested changes

2016-10-24 04:54 UTC, akariv commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file from the PR, thanks!

2016-10-24 04:54 UTC, akariv commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file from the PR, thanks!
(Also make sure it's ignored in the .gitignore file)

2016-10-24 04:54 UTC, akariv commented on .pydevproject
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Please remove this file from the PR, thanks!
(Also make sure it's ignored in the .gitignore file)

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/manager/validators.py
> +    assert (type(stream) == bytes)
Why was this added?

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/tests/test_eu2014_10.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file is here but is not tested?

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/tests/book.xml
> +<?xml version="1.0"?>
This file is here but is not tested?

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +        nameLst.append({"path": wrap(csvName)})
please use 'url' and not 'path'

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +sys.path.append('..')
Why is this line needed?

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +    if url.find('http') == -1:
better to write:
`if not url.startswith('http')`

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +    orginBaseName = os.path.basename(url).strip(' ')
Why is `strip(' ')` needed here?

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +        cmd = "xml2csv {} -a 135 >> {}".format(url, fd.name)
Please use the `subprocess` python module and read the invocation's stdout instead of writing to a temporary file.

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +                #tmpFile = ""
no commented out code please :)

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +                testPath = "xml-adapter/tests"
Why is there test related code in here???

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +def split_into_single_csvs(filename, orginBaseName, tableSeparator="\n\n\n"):
This function should NOT write all the CSV files to disk.
You should have one function for getting the list of CSVs (for the `json` request).
You should have another function for extracting _one_ CSV file into stdout (without saving it to disk).
**No test specific code is allowed!**

2016-10-24 04:54 UTC, akariv commented on os_fdp_adapters/xml-adapter/xml_to_fdp.py
> +    filename = fetch_local_filename(filename)
This entire code block doesn't make sense.

`fetch_local_filename` downloads an external URL - but the filename here is not a valid URL (as you appended `.csv` to it).
Then you open the CSV file, read it, parse it and encode it again as CSV - why??

2018-08-30 13:56 UTC, closed without merging